---
- hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: Clear pagecache, dentries, and inodes
      shell: sudo sync && sudo sh -c 'echo 1 > /proc/sys/vm/drop_caches'
      register: clear_cache_output
      changed_when: false

    - name: Print message when caches are cleared
      debug:
        msg: "Caches have been cleared."
      when: clear_cache_output.stdout != "" and clear_cache_output.rc == 0

    - name: Print message when caches are not cleared
      debug:
        msg: "Caches were not cleared."
      when: clear_cache_output.stdout == "" or clear_cache_output.rc != 0
