---
- name: Create Docker Network with Subnet and Gateway
  hosts: all
  become: yes

  tasks:
    - name: Create Docker network with custom subnet and gateway
      docker_network:
        name: ma_reseau  # corrected the spelling of "réseau"
        state: present
        config:
          - subnet: "192.168.100.0/24"
            gateway: "192.168.100.1"
