---
- name: Shutdown the Debian machine
  hosts: your_target_host  # Replace with your target host or group
  remote_user: your_remote_user  # Replace with your remote user
  become: yes
  become_method: sudo

  tasks:
    - name: Shutdown the machine
      command: /sbin/shutdown -h now
