---
- name: Shutdown the Debian machine
  hosts: all  # Replace with your target host or group
  remote_user: debian  # Replace with your remote user
  become: yes
  become_method: sudo
  become_exe: /usr/bin/sudo

  tasks:
    - name: Shutdown the machine
      command: /sbin/reboot
