---
- name: Update Debian System
  hosts: all  # Replace with your target host or group
  remote_user: your_remote_user  # Replace with your remote user
  become: yes
  become_method: sudo
  become_user: debian

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: safe
        autoremove: yes
        autoclean: yes
