---
- name: Mise à jour des paquets et installation de mongodb-org-tools
  hosts: all
  become: yes
  tasks:
    - name: Mise à jour des paquets
      command: apt update
      become: no

    - name: Installation de mongodb-org-tools
      command: apt install -y mongodb-org-tools
      become: yes
