---
---
- hosts: all  # Spécifie les hôtes sur lesquels exécuter le playbook
  become: true  # Pour exécuter en tant qu'utilisateur root
  gather_facts: no  # Ne collecte pas les faits sur les hôtes

  tasks:
    - name: istallation complet
      shell: |
        sudo docker volume create portainer_data && \
        sudo docker run -d -p 9000:9000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
        
