---
- hosts: all
  become: true  # Pour exécuter en tant qu'utilisateur root
  
  tasks:
    - name: Create directory
      file:
        path: /home/debian/Testebe # Spécifie le chemin du dossier à créer
        state: testebebe  # Indique qu'il s'agit d'un dossier à créer
