---
- name: Install net-tools on Debian
  hosts: all
  become: true  # To execute as the root user

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install net-tools
      apt:
        name: net-tools
        state: present
