---
- name: Deploy Nginx Proxy Manager with Docker Compose
  hosts: all
  become: true

  tasks:
    - name: Create the directory for Nginx Proxy Manager
      ansible.builtin.file:
        path: /opt/nginx-proxy-manager
        state: directory
        mode: '0755'

    - name: Copy the Docker Compose file for Nginx Proxy Manager
      ansible.builtin.copy:
        content: |
          version: '3'
          services:
            nginx-proxy-manager:
              image: jlesage/nginx-proxy-manager
              container_name: nginx-proxy-manager
              restart: always
              ports:
                - "80:80"
                - "81:81"
                - "443:443"
              networks:
                - nginx_proxy_network

          volumes:
            nginx_proxy_data:

          networks:
            nginx_proxy_network:
              driver: bridge
              ipam:
                config:
                  - subnet: "192.168.200.0/24"
                    gateway: "192.168.200.1"

        dest: /opt/nginx-proxy-manager/docker-compose.yml

    - name: Create the volume directories for Nginx Proxy Manager
      ansible.builtin.file:
        path: "/opt/nginx-proxy-manager/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - nginx_proxy_data

    - name: Start Nginx Proxy Manager with Docker Compose
      ansible.builtin.command: docker-compose -f /opt/nginx-proxy-manager/docker-compose.yml up -d
