---
- name: Install Git
  hosts: your_target_servers
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Git
      apt:
        name: git
        state: present
      become: yes
