---
- hosts: host
  become: true  # Pour exécuter en tant qu'utilisateur root

  tasks:
    - name: Copier le fichier Docker Compose de Portainer
      ansible.builtin.copy:
        content: |
          version: '3'
          services:
            portainer:
              image: portainer/portainer-ce
              ports:
                - "9000:9000"
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock
                - portainer_data:/data
        dest: /opt/portainer/docker-compose.yml

    - name: Créer le volume pour les données de Portainer
      ansible.builtin.command: docker volume create portainer_data
      ignore_errors: yes  # Ignore l'erreur si le volume existe déjà

    - name: Démarrer Portainer avec Docker Compose
      ansible.builtin.command: docker-compose -f /opt/portainer/docker-compose.yml up -d
