---
- hosts: all
  become: true  # Pour exécuter en tant qu'utilisateur root

  tasks:
    - name: Créer le répertoire ~/portainer
      ansible.builtin.file:
        path: ~/docker/portainer
        state: directory
        mode: '0755'

    - name: Copier le fichier Docker Compose de Portainer
      ansible.builtin.copy:
        content: |
          version: '3'
          services:
            portainer:
              image: portainer/portainer-ce
              restart: always
              ports:
                - "9000:9000"
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock
                - portainer_data:/data

          volumes:
            portainer_data:
        dest: ~/docker/portainer/docker-compose.yml

    - name: Créer le volume pour les données de Portainer
      ansible.builtin.command: docker volume create portainer_data
      ignore_errors: yes  # Ignore l'erreur si le volume existe déjà

    - name: Démarrer Portainer avec Docker Compose
      ansible.builtin.command: docker-compose -f ~/docker/portainer/docker-compose.yml up -d

