---
- hosts: all
  become: true  # Pour exécuter en tant qu'utilisateur root

- name: Update package cache
  apt:
    update_cache: yes

- name: Upgrade all packages
  apt:
    upgrade: yes
    autoremove: yes
    autoclean: yes
