---
- name: Run docker-compose up -d from Git
  hosts: all
  become: true

  tasks:
    - name: Run docker-compose up -d
      command: "/home/johfanang/docker/docker-compose up -d"
      args:
        chdir: /home/johfanang/docker
