---
- name: Run Docker Compose
  hosts: all
  become: true
  tasks:
    #- name: Change directory to where docker-compose.yml is located
     # command: docker compose -f /home/johfanang/docker/docker-compose.yml up -d
    - name: Change directory to where docker-compose.yml is located
      command: docker compose -f /home/johfanang/docker/docker-compose.yml down
     
