---
- name: Run Docker Compose
  hosts: all
  become: true
  tasks:
    - name: kill container
      command: docker compose -f /home/johfanang/docker/docker-compose_br.yml down

    - name: up container
      command: docker compose -f /home/johfanang/docker/docker-compose_br.yml up -d
     
