---
- name: Run Docker Compose
  hosts: all
  become: true
  tasks:
    - name: Change directory to where docker-compose.yml is located
      command: /home/johfanang/docker/docker-compose up -d
     
