---
- name: Install tailscale on vps
  hosts: all  # Replace with your target host or group
  #remote_user: debian  # Replace with your remote user
  become: yes
  become_method: sudo
  #become_user: debian

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install tailscale
      apt:
        name: tailscale
        state: present

