---
- name: Install Tailscale on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Download Tailscale Debian package
      get_url:
        url: "https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}/tailscale_{{ tailscale_version }}_amd64.deb"
        dest: /tmp/tailscale.deb

    - name: Install Tailscale
      apt:
        deb: /tmp/tailscale.deb
        state: present

    - name: Set up Tailscale
      command: tailscale up --authkey={{ tailscale_authkey }}
