---
- name: Install tailscale on vps
  hosts: all  # Remplacer par votre hôte cible ou groupe
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: no

    - name: Run Tailscale install script
      shell: curl -fsSL https://tailscale.com/install.sh | sudo sh
    
    
